from dataclasses import dataclass
from typing import List, Dict
from events.tags import EventTag

@dataclass
class AgendaTemplate:
    id: str
    title: str
    description: str
    tags: List[EventTag]
    choices: List[Dict]
    start_year: int = 1960
    end_year: int = 1991

ECONOMY_AGENDAS: List[AgendaTemplate] = [
    # 🟦 1960–1969: Оттепель, целина, начало хозрасчёта
    AgendaTemplate("ind_kosygin_reform", "О переводе предприятий на хозрасчёт и самофинансирование", 
                   "Реформа 1965 года расширяет самостоятельность заводов. Директора получают право формировать фонды развития.", 
                   [EventTag.ECONOMY, EventTag.CADRES], 
                   [{"text": "Распространить на все отрасли", "effects": {"stability": 3, "budget": 1, "support": 4, "ideology": -3}},
                    {"text": "Ограничить реформу машиностроением", "effects": {"stability": 1, "budget": 0, "support": 1, "ideology": -1}},
                    {"text": "Вернуться к жёсткому централизованному планированию", "effects": {"stability": -2, "budget": -2, "support": -3, "ideology": 4}}],
                   1965, 1972),
    AgendaTemplate("agro_grain_1963", "О состоянии хлебных ресурсов и закупках зерна за рубежом", 
                   "Неурожай в Поволжье создал дефицит зерна. Требуется санкционирование валютных ассигнований на импорт.", 
                   [EventTag.ECONOMY, EventTag.AGRICULTURE, EventTag.FOREIGN],
                   [{"text": "Разрешить закупки в Канаде и США", "effects": {"stability": 3, "budget": -4, "support": 4, "ideology": -3}},
                    {"text": "Ввести карточную систему в ряде регионов", "effects": {"stability": -3, "budget": 0, "support": -5, "ideology": 1}},
                    {"text": "Мобилизовать резервы и ужесточить нормирование", "effects": {"stability": -1, "budget": -1, "support": -2, "ideology": 2}}],
                   1963, 1968),
    AgendaTemplate("infra_housing_khrushchev", "О массовом индустриальном жилищном строительстве", 
                   "Переход к панельному домостроению позволит ликвидировать коммунальное заселение за 10–12 лет.", 
                   [EventTag.ECONOMY, EventTag.SOCIAL],
                   [{"text": "Утвердить типовые серии и ускорить сроки", "effects": {"stability": 4, "budget": -5, "support": 8, "ideology": 0}},
                    {"text": "Сохранить индивидуальное проектирование", "effects": {"stability": 0, "budget": -2, "support": 1, "ideology": 2}},
                    {"text": "Сократить объёмы в пользу промышленности", "effects": {"stability": -3, "budget": 3, "support": -4, "ideology": 3}}],
                   1960, 1968),
    AgendaTemplate("plan_9_pyatiletka", "Утверждение директив IX пятилетки (1971–1975)", 
                   "Госплан представил основные направления развития народного хозяйства. Ускоренный рост группы «Б».", 
                   [EventTag.ECONOMY],
                   [{"text": "Утвердить в полном объёме", "effects": {"stability": 2, "budget": -3, "support": 3, "ideology": 1}},
                    {"text": "Скорректировать в пользу потребительского сектора", "effects": {"stability": 1, "budget": -2, "support": 5, "ideology": -2}},
                    {"text": "Вернуть на доработку с учётом ресурсных ограничений", "effects": {"stability": -1, "budget": 1, "support": 0, "ideology": 0}}],
                   1970, 1975),
    AgendaTemplate("agro_nechernozeme", "О развитии мелиорации и освоении Нечерноземья", 
                   "Программа подъёма сельского хозяйства в центральных и северных областях.", 
                   [EventTag.ECONOMY, EventTag.AGRICULTURE],
                   [{"text": "Утвердить программу с полным финансированием", "effects": {"stability": 2, "budget": -5, "support": 3, "ideology": 1}},
                    {"text": "Сократить объёмы до пилотных зон", "effects": {"stability": 0, "budget": 2, "support": 0, "ideology": 0}},
                    {"text": "Перенаправить средства на целину", "effects": {"stability": 1, "budget": -2, "support": -1, "ideology": 2}}],
                   1974, 1980),
    AgendaTemplate("energy_siberia_oil", "Об освоении нефтегазовых месторождений Западной Сибири", 
                   "Самотлор, Уренгой требуют масштабных капиталовложений и трубопроводов.", 
                   [EventTag.ECONOMY, EventTag.FOREIGN],
                   [{"text": "Придать проекту статус всенародной стройки", "effects": {"stability": 4, "budget": -7, "support": 5, "ideology": 2}},
                    {"text": "Осваивать поэтапно с привлечением иностранных кредитов", "effects": {"stability": 2, "budget": -4, "support": 2, "ideology": -2}},
                    {"text": "Сосредоточиться на Поволжье и Баку", "effects": {"stability": 0, "budget": 2, "support": -1, "ideology": 1}}],
                   1973, 1985),
    AgendaTemplate("trade_western_loans", "О привлечении западных кредитов под закупку промышленных линий", 
                   "Европейские банки предлагают долгосрочные займы под 4–6% годовых.", 
                   [EventTag.ECONOMY, EventTag.FOREIGN],
                   [{"text": "Привлечь кредиты на $2 млрд", "effects": {"stability": 2, "budget": 3, "support": 1, "ideology": -2}},
                    {"text": "Ограничиться бартерными сделками", "effects": {"stability": 0, "budget": 0, "support": 0, "ideology": 1}},
                    {"text": "Отказаться от займов во избежание долговой зависимости", "effects": {"stability": 1, "budget": -2, "support": 2, "ideology": 3}}],
                   1972, 1982),
    AgendaTemplate("ind_machine_tools", "О состоянии станкостроения и приборостроения", 
                   "Отставание в выпуске ЧПУ и высокоточного оборудования. Переориентация на микроэлектронику.", 
                   [EventTag.ECONOMY, EventTag.SCIENCE],
                   [{"text": "Создать межотраслевой научно-производственный комплекс", "effects": {"stability": 2, "budget": -4, "support": 2, "ideology": -1}},
                    {"text": "Закупить лицензии у западных фирм", "effects": {"stability": 1, "budget": -3, "support": 1, "ideology": -3}},
                    {"text": "Сохранить текущие темпы модернизации", "effects": {"stability": 0, "budget": 0, "support": 0, "ideology": 1}}],
                   1975, 1983),
    AgendaTemplate("consumer_goods_push", "О расширении производства товаров народного потребления", 
                   "Дефицит обуви, тканей, бытовой техники. Запрос на перераспределение сырья.", 
                   [EventTag.ECONOMY, EventTag.SOCIAL],
                   [{"text": "Перенаправить 15% ресурсов в группу «Б»", "effects": {"stability": 4, "budget": -3, "support": 7, "ideology": -2}},
                    {"text": "Увеличить импорт готовых изделий", "effects": {"stability": 2, "budget": -4, "support": 3, "ideology": -3}},
                    {"text": "Сохранить приоритет тяжёлой промышленности", "effects": {"stability": -2, "budget": 2, "support": -4, "ideology": 3}}],
                   1970, 1980),
    AgendaTemplate("trade_comecon", "О расширении внешнеторговых связей со странами СЭВ", 
                   "Углубление специализации, расчёты в переводных рублях, совместные НТЦ.", 
                   [EventTag.ECONOMY, EventTag.SOCIALIST_BLOC],
                   [{"text": "Утвердить программу интеграции", "effects": {"stability": 2, "budget": -1, "support": 2, "ideology": 2}},
                    {"text": "Ограничиться поставками сырья в обмен на оборудование", "effects": {"stability": 0, "budget": 1, "support": 0, "ideology": 0}},
                    {"text": "Свернуть торговлю в пользу расчётов в конвертабельной валюте", "effects": {"stability": 1, "budget": -3, "support": -1, "ideology": -2}}],
                   1971, 1984),
    AgendaTemplate("crisis_budget_deficit", "О ликвидации дефицита госбюджета и сокращении расходов", 
                   "Рост дотаций предприятиям и военные расходы создают хронический дефицит.", 
                   [EventTag.ECONOMY, EventTag.CRISIS],
                   [{"text": "Сократить дотации нерентабельным заводам", "effects": {"stability": 1, "budget": 5, "support": -4, "ideology": -1}},
                    {"text": "Ввести акцизы на алкоголь и табак", "effects": {"stability": -1, "budget": 4, "support": -5, "ideology": 0}},
                    {"text": "Покрыть дефицит за счёт эмиссии", "effects": {"stability": 0, "budget": 2, "support": -2, "ideology": -2}}],
                   1978, 1985),
    AgendaTemplate("agro_food_prog_1982", "О реализации Продовольственной программы 1982 года", 
                   "Комплекс мер по увеличению производства мяса, молока, овощей. Создание агропромышленных объединений.", 
                   [EventTag.ECONOMY, EventTag.AGRICULTURE, EventTag.SOCIAL],
                   [{"text": "Утвердить программу целиком", "effects": {"stability": 3, "budget": -6, "support": 6, "ideology": 1}},
                    {"text": "Ограничить развитие личных подсобных хозяйств", "effects": {"stability": 1, "budget": -3, "support": 2, "ideology": 4}},
                    {"text": "Разрешить арендные отношения в колхозах", "effects": {"stability": 2, "budget": -4, "support": 5, "ideology": -4}}],
                   1982, 1987),
    AgendaTemplate("perestroika_enterprise_law", "О Законе о государственном предприятии (1987)", 
                   "Предприятия переходят на полный хозрасчёт, самофинансирование и самоуправление.", 
                   [EventTag.ECONOMY, EventTag.CADRES],
                   [{"text": "Внедрить закон без ограничений", "effects": {"stability": 1, "budget": 2, "support": 4, "ideology": -5}},
                    {"text": "Сохранить госзаказ на 70% продукции", "effects": {"stability": 2, "budget": 0, "support": 1, "ideology": -2}},
                    {"text": "Отложить реформу до стабилизации цен", "effects": {"stability": 0, "budget": -1, "support": 0, "ideology": 3}}],
                   1987, 1990),
    AgendaTemplate("perestroika_cooperatives", "О развитии кооперативного движения в сфере услуг и производства", 
                   "Легализация частного предпринимательства в форме кооперативов. Утверждение налоговых ставок.", 
                   [EventTag.ECONOMY, EventTag.SOCIAL],
                   [{"text": "Разрешить кооперативы с налогом 40%", "effects": {"stability": 2, "budget": 3, "support": 3, "ideology": -4}},
                    {"text": "Ограничить деятельность бытовыми услугами", "effects": {"stability": 1, "budget": 1, "support": 0, "ideology": -1}},
                    {"text": "Запретить как проявление мелкобуржуазной стихии", "effects": {"stability": -2, "budget": -2, "support": -3, "ideology": 5}}],
                   1986, 1990),
    AgendaTemplate("perestroika_pavlov_reform", "О проведении денежной реформы и обмене крупных купюр (1991)", 
                   "Изъятие из обращения банкнот 50 и 100 рублей образца 1961 года. Ограничение сроков обмена.", 
                   [EventTag.ECONOMY, EventTag.CRISIS],
                   [{"text": "Провести обмен с жёсткими лимитами", "effects": {"stability": -5, "budget": 4, "support": -8, "ideology": 0}},
                    {"text": "Ограничиться конфискацией у теневиков", "effects": {"stability": -1, "budget": 1, "support": 2, "ideology": 1}},
                    {"text": "Отменить реформу и выпустить новые купюры позже", "effects": {"stability": 2, "budget": -3, "support": 3, "ideology": -1}}],
                   1990, 1991),
    AgendaTemplate("crisis_shadow_economy", "О борьбе с нетрудовыми доходами и теневой экономикой", 
                   "Спекуляция, цеховики, махинации с госимуществом. Усиление контроля и ужесточение наказаний.", 
                   [EventTag.ECONOMY, EventTag.CRISIS, EventTag.CADRES],
                   [{"text": "Создать спецкомиссии при МВД и КГБ", "effects": {"stability": 2, "budget": 2, "support": -3, "ideology": 4}},
                    {"text": "Легализовать часть деятельности через кооперативы", "effects": {"stability": 1, "budget": 3, "support": 1, "ideology": -3}},
                    {"text": "Игнорировать как временное явление", "effects": {"stability": -2, "budget": -1, "support": 0, "ideology": 0}}],
                   1983, 1990),
    AgendaTemplate("consumer_coupons_1990", "О введении талонов на отдельные виды продовольствия и промтоваров", 
                   "Рост денежной массы при неизменном товарном предложении требует нормирования потребления.", 
                   [EventTag.ECONOMY, EventTag.CRISIS, EventTag.SOCIAL],
                   [{"text": "Ввести талоны на сахар, мясо, мыло", "effects": {"stability": -2, "budget": 1, "support": -6, "ideology": 0}},
                    {"text": "Повысить розничные цены на 30%", "effects": {"stability": -4, "budget": 3, "support": -7, "ideology": -1}},
                    {"text": "Разрешить свободную продажу через кооперативы", "effects": {"stability": 1, "budget": 2, "support": 2, "ideology": -4}}],
                   1989, 1991),
    AgendaTemplate("ind_chemical_push", "Об ускоренном развитии химической промышленности", 
                   "Создание мощностей по производству минеральных удобрений, синтетических волокон и пластмасс.", 
                   [EventTag.ECONOMY, EventTag.SCIENCE],
                   [{"text": "Утвердить строительство 12 новых комбинатов", "effects": {"stability": 2, "budget": -5, "support": 3, "ideology": 0}},
                    {"text": "Модернизировать существующие предприятия", "effects": {"stability": 1, "budget": -2, "support": 1, "ideology": 0}},
                    {"text": "Отложить реализацию в пользу ВПК", "effects": {"stability": 0, "budget": 3, "support": -1, "ideology": 3}}],
                   1965, 1975),
    AgendaTemplate("energy_nuclear", "О расширении программы строительства атомных электростанций", 
                   "АЭС позволяют снизить зависимость от органического топлива. Утверждение площадок и мер безопасности.", 
                   [EventTag.ECONOMY, EventTag.SCIENCE],
                   [{"text": "Утвердить строительство 10 блоков ВВЭР", "effects": {"stability": 2, "budget": -6, "support": 3, "ideology": 0}},
                    {"text": "Развивать только тепловую и гидрогенерацию", "effects": {"stability": 0, "budget": 1, "support": 0, "ideology": 2}},
                    {"text": "Заморозить программу до отработки технологии", "effects": {"stability": 0, "budget": 2, "support": -1, "ideology": 1}}],
                   1970, 1986),
    AgendaTemplate("infra_bam_construction", "О строительстве Байкало-Амурской магистрали", 
                   "БАМ обеспечит доступ к месторождениям Восточной Сибири. Мобилизация комсомольских ресурсов.", 
                   [EventTag.ECONOMY, EventTag.SOCIAL],
                   [{"text": "Утвердить ударную стройку с льготами участникам", "effects": {"stability": 3, "budget": -8, "support": 5, "ideology": 3}},
                    {"text": "Строить поэтапно в мирном режиме", "effects": {"stability": 1, "budget": -4, "support": 2, "ideology": 0}},
                    {"text": "Перенаправить средства на БАТ", "effects": {"stability": 0, "budget": -2, "support": 0, "ideology": 1}}],
                   1974, 1989),
    AgendaTemplate("plan_val_output", "О замене показателя «валовая продукция» на «реализованную продукцию»", 
                   "Минфин и Госплан предлагают устранить стимулы к производству невостребованных товаров.", 
                   [EventTag.ECONOMY],
                   [{"text": "Внедрить показатель повсеместно", "effects": {"stability": 2, "budget": 2, "support": 2, "ideology": -1}},
                    {"text": "Провести эксперимент на 50 предприятиях", "effects": {"stability": 0, "budget": 0, "support": 1, "ideology": 0}},
                    {"text": "Сохранить валовые показатели как базовые", "effects": {"stability": 0, "budget": -1, "support": -2, "ideology": 2}}],
                   1966, 1973)
]